openapi: 3.0.1
info:
  title: BookStoreAPI
  description: API Definition of BookStoreAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/bookstore
paths:
  /books:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /books/{book_id}:
    get:
      parameters:
      - name: book_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
      - name: book_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: book_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /orders:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /orders/{order_id}:
    get:
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
